server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lmx?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null
#  web:
#    resources:
#      static-locations: classpath:/static/
mybatis-plus:
  type-aliases-package: org.lanqiao.pojo
  configuration:
    map-underscore-to-camel-case: true
    #    开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.hmdp: debug
thymeleaf:
    cache: false
    check-template-location: 'true'
    mode: HTML5
    prefix: 'classpath:/templates/'
    suffix: '.html'
    servlet:
      content-type: 'text/html '
    encoding: UTF-8
